name: Analyze

on:
  workflow_dispatch:
    inputs:
      input_csv:
        description: 'input CSV filename'
        required: true
        default: 'backtest_all_enriched.csv'

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Run analyze
        run: python3 analyze2.py ${{ github.event.inputs.input_csv }} | tee analyze_result.txt

      - name: Commit result
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add analyze_result.txt
          git diff --staged --quiet || git commit -m "analyze ${{ github.event.inputs.input_csv }}"
          git push
